config/routes.rb
Rails.application.routes.draw do
  resources :ingredients do
    post :update_row_order, on: :collection
  end

  resources :products do
    resources :ingredients do
      post :update_row_order, on: :collection
    end
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  # this will allow drag-n-drop sorting functionality
  include RankedModel
  ranks :row_order, :with_same => :list_id

  belongs_to :list
  scope :master_list_ingredients, -> { where(list_id: 1) }

  validates :name, presence: true
  validates :step, presence: true
  validates :track, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :product
  has_many :ingredients, dependent: :destroy
  scope :master_list, -> { where(name: 'master') }

  amoeba do
    enable
    clone [:ingredients]
    append name: " copy"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_one :list, dependent: :destroy
  has_many :ingredients, through: :list
  after_create :make_copy_of_master_list
  scope :sorted, -> { order(:created_at) }

  validates :name, presence: true, length: { maximum: 255,
                               message: "Please enter a shorter product name" }

  # allows duplication the master list upon creation of a product
  amoeba do
    enable
  end

  def set_copy_of_list_to_new_product(list)
    list.product_id = self.id
  end

  def make_copy_of_master_list
    master = List.master_list.first
    copied_list = master.amoeba_dup
    set_copy_of_list_to_new_product(copied_list)
    copied_list.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :destroy]

  def new
    @ingredient = Ingredient.new
  end

  def index
    @ingredients = Ingredient.master_list_ingredients.rank(:row_order)
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    set_ingredient_to_default_list(@ingredient)

    if @ingredient.save
      redirect_to ingredients_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @ingredient.update_attributes(ingredient_params)
      redirect_to ingredients_url
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_url
  end

  def update_row_order
    @ingredient = Ingredient.find(ingredient_params[:ingredient_id])
    @ingredient.row_order_position = ingredient_params[:row_order_position]
    @ingredient.save

    # this is a POST action, updates sent via AJAX, no view rendered
    render nothing: true
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:name, :step, :track,
                                            :row_order_position, :ingredient_id)
    end

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # initially every ingredient added to system will belong to the first list
    # couldn't put it in ingredient model because when duplicating with amoeba
    # it set those ingredients to master list as well instead of the new list
    def set_ingredient_to_default_list(ingredient)
      ingredient.list_id = List.master_list.id
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :set_product_ingredients, only: [:edit, :update]

  def index
    @products = Product.sorted
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to products_url
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  private
    def product_params
      params.require(:product).permit(:name, :description)
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def set_product_ingredients
      @ingredients = Product.find(params[:id]).ingredients.rank(:row_order).all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/ingredients/_form_fields.html.erb
<div class="row">
  <div class="col-sm-4 col-md-8 col-xs-12">
    <%= f.text_field :name, placeholder: "Enter ingredient name",
                                      class: "form-control", autofocus: true %>
  </div>

  <div class="col-sm-4 col-xs-12">
    <%= render partial: 'shared/error_messages',
                          locals: {object: @ingredient, errors_for: 'name' } %>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 col-md-8 col-xs-12">
    <%= f.select :step, options_for_select(
        [
          ['Team','Team'],
          ['Ideation','Ideation'],
          ['Test','Test'],
          ['Plan','Plan'],
          ['Design','Design'],
          ['Develop','Develop'],
          ['Expose','Expose'],
          ['Grow','Grow'],
          ['Exit','Exit']
        ]
      ), {prompt: 'Select an ingredient step'}, {class: "form-control"} %>
  </div>

  <div class="col-sm-4 col-xs-12">
    <%= render partial: 'shared/error_messages',
                  locals: {object: @ingredient, errors_for: 'step' } %>
  </div>
</div>


<div class="row">
  <div class="col-sm-4 col-md-8 col-xs-12">
    <%= f.select :track, options_for_select(
        [
          ['Business', 'Business'],
          ['Culture', 'Culture'],
          ['Product', 'Product']
        ]
      ), {prompt: 'Select a track'}, {class: "form-control"} %>
  </div>

  <div class="col-sm-4 col-xs-12">
    <%= render partial: 'shared/error_messages',
                          locals: {object: @ingredient, errors_for: 'track' } %>
  </div>
</div>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/edit.html.erb
<h1 class="page_name">Ingredient</h1>

<%= form_for @ingredient do |f| %>
    <%= render partial: "form_fields", locals: {f: f} %>

    <!-- Buttons -->
    <div class="row">
      <div class="col-xs-12 hidden-xs">
        <%= f.submit "Save ingredient", class: "btn btn-primary" %>
        <%= link_to "Cancel", ingredients_path, class: "btn btn-default" %>
        <%= link_to "Delete", '#', data: {toggle: "modal",
                          target: "#delIngredient"}, class: "btn btn-danger" %>
      </div>

      <div class="col-xs-12 visible-xs-block">
        <%= f.submit "Save ingredient", class: "btn btn-primary btn-sm" %>
        <%= link_to "Cancel", ingredients_path,
                                    class: "btn btn-default btn-sm" %>
        <%= link_to "Delete", '#', data: {toggle: "modal",
                    target: "#delIngredient"}, class: "btn btn-danger btn-sm" %>
      </div>
    </div>

    <!-- Delete Modal -->
    <div class="modal fade" id="delIngredient">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Delete <%= @ingredient.name %></h4>
          </div>

          <div class="modal-body">
            <p>Deleting this ingredient will remove it from the system forever.
            Do you feel certain you want to do this?</p>
          </div>

          <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= link_to "Delete", ingredient_path(@ingredient),
                                    method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/ingredients/index.html.erb
<h1 class="page_name">Ingredients</h1>

<%= link_to "Add", new_ingredient_path, class: "btn btn-default" %>
<%= link_to "Reorder", "javascript:void(0)", class: "btn btn-info reorder" %>

<%= render partial: "shared/ingredient_list",
                    locals: {ingredients: @ingredients} %>

app/views/ingredients/new.html.erb
<h1 class="page_name">Ingredients</h1>

<p>These ingredients will define your workflow.</p>

<%= form_for @ingredient do |f| %>
    <%= render partial: 'form_fields', locals: {f: f} %>

    <!-- Buttons -->
    <div class="row">
      <div class="col-sm-9 col-xs-12">
        <%= f.submit "Create ingredient", class: "btn btn-primary" %>
        <%= link_to "Cancel", ingredients_path, class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Core</title>
  <meta name="viewport" content="width=device-width", initial-scale="1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "shared/nav" %>

  <div class="container-fluid">
    <div class="col-md-10 col-md-offset-1 content">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/products/_form_fields.html.erb
<div class="row">
  <div class="col-sm-8 col-xs-12">
    <%= f.text_field :name, placeholder: "Enter product name",
                                      class: "form-control", autofocus: true %>
  </div>

  <div class="col-sm-4 col-xs-12">
    <%= render partial: 'shared/error_messages',
                          locals: {object: @product, errors_for: 'name'} %>
  </div>
</div>

<div class="row">
  <div class="col-sm-8 col-xs-12">
    <%= f.text_area :description,
                        placeholder: "Enter a short description (optional)",
                        class: "form-control", rows: "3" %>
  </div>

  <div class="col-sm-4 col-xs-12">
    <%= render partial: 'shared/error_messages',
                        locals: {object: @product, errors_for: 'description'} %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6">
    <h1 class="page_name">Product</h1>

    <%= form_for @product do |f| %>
      <%= render partial: "form_fields", locals: {f: f} %>

      <!-- Buttons -->
      <div class="row">
        <div class="col-xs-12 hidden-xs">
          <%= f.submit "Save product", class: "btn btn-primary" %>
          <%= link_to "Cancel", products_path, class: "btn btn-default" %>
          <%= link_to "Delete", '#', data: {toggle: "modal",
                          target: "#delProduct"}, class: "btn btn-danger" %>
        </div>

        <div class="col-xs-12 visible-xs-block">
          <%= f.submit "Save product", class: "btn btn-primary btn-sm" %>
          <%= link_to "Cancel", products_path, class: "btn btn-default btn-sm" %>
          <%= link_to "Delete", '#', data: {toggle: "modal",
                    target: "#delProduct"}, class: "btn btn-danger btn-sm" %>
        </div>
      </div>

      <!-- Delete Modal -->
      <div class="modal fade" id="delProduct">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Delete <%= @product.name %></h4>
            </div>

            <div class="modal-body">
              <p>This will delete your product and all of its data.
               Are you sure you want to delete it?</p>
            </div>

            <div class="modal-footer">
              <button class="btn btn-default" data-dismiss="modal">Cancel</button>
              <%= link_to "Delete", product_path(@product),
                                      method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-6">
    <h1 class="page_name">Ingredients</h1>
    <hr>
    <%= render partial: "shared/ingredient_list",
                                            locals: {ingredient: @ingredient} %>
  </div>
</div>

app/views/products/index.html.erb
<h1 class="page_name">Products</h1>

<%= link_to "Add", new_product_path, class: "btn btn-default" %>

<div class="list">
  <% @products.each do |product| %>
    <div class="row">
      <div class="col-md-2 col-sm-2 col-xs-4">
        <h4><%= link_to product.name, edit_product_path(product) %></h4>
      </div>

      <div class="col-md-10 col-sm-10 col-xs-8">
        <h4><%= product.description %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1 class="page_name">Products</h1>

<%= form_for @product do |f| %>
  <%= render partial: 'form_fields', locals: {f: f} %>

  <div class="row">
    <div class="col-sm-9 col-xs-12">
      <%= f.submit "Create product", class: "btn btn-primary" %>
      <%= link_to "Cancel", products_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.messages[errors_for.to_sym].each do |message| %>
    <span class="text-danger"><%= message %></span>
  <% end %>
<% end %>

app/views/shared/_ingredient_list.html.erb
<table class="sortable">
  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr class="ingredient" data-ingredient-id=<%= "#{ingredient.id}" %>>
        <td class="col-md-4">
          <h4>
            <span><i></i></span>
            <%= link_to ingredient.step, edit_ingredient_path(ingredient) %>
          </h4>
        </td>
        <td class="col-md-8">
          <h4><%= ingredient.name %></h4>
        </td>
      </tr>
    <% end %>
  </tbody>
</ul>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <!-- Brand Name -->
      <a href="#" class="navbar-brand">Core</a>

      <!-- Button for toggling when collapse -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#core_nav">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- navigation links -->
    <div class="collapse navbar-collapse" id="core_nav">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= products_path %>">Products</a></li>
        <li><a href="<%= ingredients_path %>">Ingredients</a></li>
      </ul>
    </div>
  </div>
</nav>